export const GET_PRODUCTS_LIST = 'GET_PRODUCTS_LIST';
export const GET_PRODUCTS_LIST_SUCCESS = 'GET_PRODUCTS_LIST_SUCCESS';
export const GET_PRODUCTS_LIST_FAIL = 'GET_PRODUCTS_LIST_FAIL';
export const ADD_PRODUCT_CAR = 'ADD_PRODUCT_CAR';
export const REMOVE_PRODUCT_CAR = 'REMOVE_PRODUCT_CAR';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';